server:
  port: 3001
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aplazo?currentSchema=public
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/aplazo?currentSchema=public
    user: developer
    password: developer
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

logging:
  level:
    com.aplazo.bnpl: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

jwt:
  secret: ${JWT_SECRET:0YHdlHtRTQ3q2mPQR0UlYioITWXrt4BV}
  expiration: ${JWT_EXPIRATION:86400000}
